// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_BLOOD_OXY_H
#define UI_BLOOD_OXY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_blood_oxy
extern void ui_blood_oxy_screen_init(void);
extern void ui_blood_oxy_screen_destroy(void);
extern void ui_event_blood_oxy(lv_event_t * e);
extern lv_obj_t * ui_blood_oxy;
extern lv_obj_t * ui_bg6;
extern lv_obj_t * ui_title_group_1;
extern void ui_event_button_down5_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down5;
extern void ui_event_button_round_buttonround(lv_event_t * e);
extern lv_obj_t * ui_button_round;
extern lv_obj_t * ui_blood_presure_group;
extern lv_obj_t * ui_blood_oxygen;
extern lv_obj_t * ui_percent;
extern lv_obj_t * ui_pulse_group;
extern lv_obj_t * ui_arc_spo2;
extern lv_obj_t * ui_precent_70;
extern lv_obj_t * ui_precent_100;
extern lv_obj_t * ui_health_dots_group;
extern lv_obj_t * ui_dot7;
extern lv_obj_t * ui_dot6;
extern lv_obj_t * ui_dot5;
extern lv_obj_t * ui_dots_group1;
extern lv_obj_t * ui_dot18;
extern lv_obj_t * ui_dot19;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

