// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_BLOOD_PRESSURE_H
#define UI_BLOOD_PRESSURE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_blood_pressure
extern void ui_blood_pressure_screen_init(void);
extern void ui_blood_pressure_screen_destroy(void);
extern void ui_event_blood_pressure(lv_event_t * e);
extern lv_obj_t * ui_blood_pressure;
extern lv_obj_t * ui_bg2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_title_group_3;
extern void ui_event_button_down7_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down7;
extern void ui_event_button_round2_buttonround(lv_event_t * e);
extern lv_obj_t * ui_button_round2;
extern lv_obj_t * ui_blood_presure_group1;
extern lv_obj_t * ui_sys_group;
extern lv_obj_t * ui_sys;
extern lv_obj_t * ui_mmhg1;
extern lv_obj_t * ui_blood_oxygen1;
extern lv_obj_t * ui_pulse_group2;
extern lv_obj_t * ui_blood_presure_group2;
extern lv_obj_t * ui_dia_group;
extern lv_obj_t * ui_dia;
extern lv_obj_t * ui_mmhg2;
extern lv_obj_t * ui_blood_oxygen2;
extern lv_obj_t * ui_health_dots_group2;
extern lv_obj_t * ui_dot12;
extern lv_obj_t * ui_dot13;
extern lv_obj_t * ui_dot11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

