// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_CALL_H
#define UI_CALL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_call
extern void ui_call_screen_init(void);
extern void ui_call_screen_destroy(void);
extern void ui_event_call(lv_event_t * e);
extern lv_obj_t * ui_call;
extern lv_obj_t * ui_bg_3;
extern lv_obj_t * ui_avatar;
extern lv_obj_t * ui_avatar_label;
extern lv_obj_t * ui_call_time;
extern lv_obj_t * ui_mute;
extern void ui_event_button_down2_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down2;
extern lv_obj_t * ui_volume_group;
extern lv_obj_t * ui_volume_percent;
extern lv_obj_t * ui_volume_image;
extern void ui_event_volume_arc(lv_event_t * e);
extern lv_obj_t * ui_volume_arc;
extern void ui_event_button_top2_buttontop(lv_event_t * e);
extern lv_obj_t * ui_button_top2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

