// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t * ui_ecg = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_bg1 = NULL;
lv_obj_t * ui_title_group_2 = NULL;
lv_obj_t * ui_button_down6 = NULL;
lv_obj_t * ui_button_round1 = NULL;
lv_obj_t * ui_pulse_group1 = NULL;
lv_obj_t * ui_health_dots_group1 = NULL;
lv_obj_t * ui_dot9 = NULL;
lv_obj_t * ui_dot8 = NULL;
lv_obj_t * ui_dot10 = NULL;
lv_obj_t * ui_chart_group = NULL;
lv_obj_t * ui_chart_ecg = NULL;
lv_obj_t * ui_chart_ecg_Xaxis = NULL;
lv_obj_t * ui_chart_ecg_Yaxis1 = NULL;
lv_obj_t * ui_chart_ecg_Yaxis2 = NULL;
// event funtions
void ui_event_ecg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        top_Animation(ui_chart_group, 0);
        opa_on_Animation(ui_pulse_group1, 100);
        opa_on_Animation(ui_button_round1, 200);
        opa_on_Animation(ui_chart_ecg, 0);
        top_Animation(ui_title_group_2, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_blood_pressure, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_pressure_screen_init);
    }
}

void ui_event_button_down6_buttondown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
    }
}

void ui_event_button_round1_buttonround(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_measuing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_measuing_screen_init);
    }
}

// build funtions

void ui_ecg_screen_init(void)
{
    ui_ecg = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ecg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ecg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ecg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_ecg);
    lv_image_set_src(ui_Image1, &ui_img_s8_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 397
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 397
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg1 = lv_image_create(ui_ecg);
    lv_image_set_src(ui_bg1, &ui_img_bg3_png);
    lv_obj_set_width(ui_bg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_title_group_2 = ui_titlegroup_create(ui_ecg);
    lv_obj_set_x(ui_title_group_2, 0);
    lv_obj_set_y(ui_title_group_2, -303);
    lv_obj_set_align(ui_title_group_2, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_x(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), 0);
    lv_obj_set_y(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), 0);
    lv_obj_set_align(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), "ECG");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_TITLE), &ui_font_Subtitle,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_title_group_2, UI_COMP_TITLEGROUP_SUBTITLE), "7 hours ago");

    ui_button_down6 = ui_buttondown_create(ui_ecg);
    lv_obj_set_x(ui_button_down6, 146);
    lv_obj_set_y(ui_button_down6, 102);

    lv_image_set_src(ui_comp_get_child(ui_button_down6, UI_COMP_BUTTONDOWN_BUTTON_DOWN_ICON), &ui_img_house_png);

    ui_button_round1 = ui_buttonround_create(ui_ecg);
    lv_obj_set_x(ui_button_round1, 0);
    lv_obj_set_y(ui_button_round1, -45);

    ui_pulse_group1 = ui_pulsegroup_create(ui_ecg);
    lv_obj_set_x(ui_pulse_group1, 0);
    lv_obj_set_y(ui_pulse_group1, 53);

    ui_health_dots_group1 = lv_obj_create(ui_ecg);
    lv_obj_set_width(ui_health_dots_group1, 102);
    lv_obj_set_height(ui_health_dots_group1, 18);
    lv_obj_set_x(ui_health_dots_group1, 0);
    lv_obj_set_y(ui_health_dots_group1, -15);
    lv_obj_set_align(ui_health_dots_group1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_health_dots_group1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_health_dots_group1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_health_dots_group1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_health_dots_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_health_dots_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_health_dots_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_health_dots_group1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot9 = lv_obj_create(ui_health_dots_group1);
    lv_obj_set_width(ui_dot9, 6);
    lv_obj_set_height(ui_dot9, 6);
    lv_obj_set_align(ui_dot9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dot9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot9, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot8 = lv_obj_create(ui_health_dots_group1);
    lv_obj_set_width(ui_dot8, 10);
    lv_obj_set_height(ui_dot8, 10);
    lv_obj_set_align(ui_dot8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dot8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot10 = lv_obj_create(ui_health_dots_group1);
    lv_obj_set_width(ui_dot10, 6);
    lv_obj_set_height(ui_dot10, 6);
    lv_obj_set_align(ui_dot10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dot10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot10, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chart_group = lv_obj_create(ui_ecg);
    lv_obj_set_height(ui_chart_group, 117);
    lv_obj_set_width(ui_chart_group, lv_pct(100));
    lv_obj_set_x(ui_chart_group, 0);
    lv_obj_set_y(ui_chart_group, -34);
    lv_obj_set_align(ui_chart_group, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_chart_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_chart_group, lv_color_hex(0x494949), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_group, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_chart_ecg = lv_chart_create(ui_chart_group);
    lv_obj_set_width(ui_chart_ecg, 503);
    lv_obj_set_height(ui_chart_ecg, 100);
    lv_obj_set_align(ui_chart_ecg, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_chart_ecg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_chart_ecg, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_chart_ecg, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_chart_ecg, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_chart_ecg, 147);
    lv_chart_set_div_line_count(ui_chart_ecg, 10, 40);
    lv_obj_set_style_bg_color(ui_chart_ecg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_ecg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_chart_ecg, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_chart_ecg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chart_ecg_Xaxis = lv_scale_create(ui_chart_ecg);
    lv_scale_set_mode(ui_chart_ecg_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_chart_ecg_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_chart_ecg_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_chart_ecg_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_chart_ecg,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_chart_ecg, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_chart_ecg_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chart_ecg_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_chart_ecg_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chart_ecg_Xaxis, 10, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_chart_ecg_Xaxis, 1, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_chart_ecg_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_chart_ecg_Xaxis, (0 > 0 ? 0 - 1 : 0) * 10 + 1);
    lv_scale_set_major_tick_every(ui_chart_ecg_Xaxis, 10 >= 1 ? 10 : 1);
    lv_scale_set_label_show(ui_chart_ecg_Xaxis, false);
    ui_chart_ecg_Yaxis1 = lv_scale_create(ui_chart_ecg);
    lv_scale_set_mode(ui_chart_ecg_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_chart_ecg_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_chart_ecg_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_chart_ecg_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_chart_ecg,
                                                                      LV_PART_MAIN) - lv_obj_get_style_border_width(ui_chart_ecg, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_chart_ecg_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chart_ecg_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chart_ecg_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chart_ecg_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chart_ecg_Yaxis1, 1, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_chart_ecg_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_chart_ecg_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_chart_ecg_Yaxis1, false);
    ui_chart_ecg_Yaxis2 = lv_scale_create(ui_chart_ecg);
    lv_scale_set_mode(ui_chart_ecg_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_chart_ecg_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_chart_ecg_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_chart_ecg_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_chart_ecg,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_chart_ecg, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_chart_ecg_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chart_ecg_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chart_ecg_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chart_ecg_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chart_ecg_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_chart_ecg_Yaxis2, (1 > 0 ? 1 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_chart_ecg_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_chart_ecg_Yaxis2, false);
    lv_chart_series_t * ui_chart_ecg_series_1 = lv_chart_add_series(ui_chart_ecg, lv_color_hex(0xEE1C18),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_chart_ecg_series_1_array[] = { 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20, 20, 21, 24, 25, 24, 22, 25, 18, 90, 10, 24, 25, 28, 38, 39, 28, 24, 23, 25, 27, 27, 25, 22, 20 };
    lv_chart_set_ext_y_array(ui_chart_ecg, ui_chart_ecg_series_1, ui_chart_ecg_series_1_array);

    lv_obj_set_style_line_width(ui_chart_ecg, 3, LV_PART_ITEMS | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_chart_ecg, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_chart_ecg, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_button_down6, ui_event_button_down6_buttondown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_round1, ui_event_button_round1_buttonround, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ecg, ui_event_ecg, LV_EVENT_ALL, NULL);

}

void ui_ecg_screen_destroy(void)
{
    if(ui_ecg) lv_obj_del(ui_ecg);

    // NULL screen variables
    ui_ecg = NULL;
    ui_Image1 = NULL;
    ui_bg1 = NULL;
    ui_title_group_2 = NULL;
    ui_button_down6 = NULL;
    ui_button_round1 = NULL;
    ui_pulse_group1 = NULL;
    ui_health_dots_group1 = NULL;
    ui_dot9 = NULL;
    ui_dot8 = NULL;
    ui_dot10 = NULL;
    ui_chart_group = NULL;
    ui_chart_ecg = NULL;

}
