// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_ECG_H
#define UI_ECG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ecg
extern void ui_ecg_screen_init(void);
extern void ui_ecg_screen_destroy(void);
extern void ui_event_ecg(lv_event_t * e);
extern lv_obj_t * ui_ecg;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_bg1;
extern lv_obj_t * ui_title_group_2;
extern void ui_event_button_down6_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down6;
extern void ui_event_button_round1_buttonround(lv_event_t * e);
extern lv_obj_t * ui_button_round1;
extern lv_obj_t * ui_pulse_group1;
extern lv_obj_t * ui_health_dots_group1;
extern lv_obj_t * ui_dot9;
extern lv_obj_t * ui_dot8;
extern lv_obj_t * ui_dot10;
extern lv_obj_t * ui_chart_group;
extern lv_obj_t * ui_chart_ecg;
extern lv_obj_t * ui_chart_ecg_Xaxis;
extern lv_obj_t * ui_chart_ecg_Yaxis1;
extern lv_obj_t * ui_chart_ecg_Yaxis2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

