// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_MEASUING_H
#define UI_MEASUING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_measuing
extern void ui_measuing_screen_init(void);
extern void ui_measuing_screen_destroy(void);
extern void ui_event_measuing(lv_event_t * e);
extern lv_obj_t * ui_measuing;
extern lv_obj_t * ui_bg7;
extern lv_obj_t * ui_pulse_group3;
extern lv_obj_t * ui_measuring;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_blood_group;
extern lv_obj_t * ui_blood1;
extern lv_obj_t * ui_blood_fill;
extern lv_obj_t * ui_blood2;
extern void ui_event_x_button(lv_event_t * e);
extern lv_obj_t * ui_x_button;
extern lv_obj_t * ui_x;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

