// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_WEATHER_2_H
#define UI_WEATHER_2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_weather_2
extern void ui_weather_2_screen_init(void);
extern void ui_weather_2_screen_destroy(void);
extern void ui_event_weather_2(lv_event_t * e);
extern lv_obj_t * ui_weather_2;
extern lv_obj_t * ui_bg5;
extern lv_obj_t * ui_weather_dots_group1;
extern lv_obj_t * ui_dot3;
extern lv_obj_t * ui_dot4;
extern lv_obj_t * ui_content;
extern lv_obj_t * ui_city_gruop_2;
extern lv_obj_t * ui_todady_weather_content;
extern lv_obj_t * ui_today_weather_group;
extern lv_obj_t * ui_today_weather_group1;
extern lv_obj_t * ui_today_weather_group2;
extern lv_obj_t * ui_today_weather_group3;
extern lv_obj_t * ui_today_weather_group4;
extern lv_obj_t * ui_today_weather_group5;
extern lv_obj_t * ui_today_weather_group6;
extern lv_obj_t * ui_today_weather_group7;
extern lv_obj_t * ui_today_weather_group8;
extern lv_obj_t * ui_days_forecast;
extern lv_obj_t * ui_week_weather_group;
extern lv_obj_t * ui_forecast_group;
extern lv_obj_t * ui_forecast_group1;
extern lv_obj_t * ui_forecast_group2;
extern lv_obj_t * ui_forecast_group3;
extern lv_obj_t * ui_forecast_group4;
extern lv_obj_t * ui_forecast_group5;
extern lv_obj_t * ui_space;
extern void ui_event_button_down4_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

