// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_WATCH_ANALOG_H
#define UI_WATCH_ANALOG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_watch_analog
extern void ui_watch_analog_screen_init(void);
extern void ui_watch_analog_screen_destroy(void);
extern void ui_event_watch_analog(lv_event_t * e);
extern lv_obj_t * ui_watch_analog;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_dots;
extern lv_obj_t * ui_date_group2;
extern lv_obj_t * ui_day2;
extern lv_obj_t * ui_month2;
extern lv_obj_t * ui_year2;
extern lv_obj_t * ui_weather_title_group_2;
extern void ui_event_button_down1_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down1;
extern lv_obj_t * ui_clock_group;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_dots_group;
extern lv_obj_t * ui_dot16;
extern lv_obj_t * ui_dot17;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

