// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef UI_WATCH_DIGITAL_H
#define UI_WATCH_DIGITAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_watch_digital
extern void ui_watch_digital_screen_init(void);
extern void ui_watch_digital_screen_destroy(void);
extern void ui_event_watch_digital(lv_event_t * e);
extern lv_obj_t * ui_watch_digital;
extern lv_obj_t * ui_bg_1;
extern lv_obj_t * ui_hour_group;
extern lv_obj_t * ui_label_hour_1;
extern lv_obj_t * ui_label_hour_2;
extern lv_obj_t * ui_label_min;
extern lv_obj_t * ui_battery_group;
extern lv_obj_t * ui_date_group;
extern lv_obj_t * ui_weather_group_1;
extern lv_obj_t * ui_weather_title_group_1;
extern lv_obj_t * ui_step_group;
extern lv_obj_t * ui_daily_mission_group;
extern void ui_event_button_top_buttontop(lv_event_t * e);
extern lv_obj_t * ui_button_top;
extern void ui_event_button_down_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down;
extern lv_obj_t * ui_sec_dot;
extern lv_obj_t * ui_weather_dots_group2;
extern lv_obj_t * ui_dot14;
extern lv_obj_t * ui_dot15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

